### ISSUE TITLE
code: 'ERR_REQUIRE_ESM' at 03-REACT-ESSENTIALS folder

### ISSUE THREAD

**Issue by jrjaca** [academind/react-complete-guide-course-resources#28]
I encountered an error after running npm run dev. Please see below's info:

---------------------

PS C:\ReactProjects\ReactTheCompleteGuide2024inclReactRouteRedux\03-REACT-ESSENTIALS> npm run dev

> react-essentials-start@0.0.0 dev
> vite

internal/modules/cjs/loader.js:1172
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\ReactProjects\ReactTheCompleteGuide2024inclReactRouteRedux\03-REACT-ESSENTIALS\node_modules\vite\bin\vite.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1172:13)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}

----------------------------

**Comment by jrjaca** [comment]
I just found it my self. Update the Node.js to the latest version.
