### ISSUE TITLE
Error Running NPM Run Dev

### ISSUE THREAD

**Issue by kjohnson2021** [academind/react-complete-guide-course-resources#36]
after running npm install, then trying to execute npm run dev, I get the following error in my Mac terminal window:

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:122:18)
    at async link (internal/modules/esm/module_job.js:42:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-essentials-start@0.0.0 dev: `vite`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-essentials-start@0.0.0 dev script.

**Comment by 010jjhere** [comment]
run (npm install) first then do it again.
maybe your device don't have nodejs installed.

**Comment by ilseojeon** [comment]
> after running npm install, then trying to execute npm run dev, I get the following error in my Mac terminal window:
> 
> SyntaxError: Unexpected reserved word at Loader.moduleStrategy (internal/modules/esm/translators.js:122:18) at async link (internal/modules/esm/module_job.js:42:21) npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! react-essentials-start@0.0.0 dev: `vite` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the react-essentials-start@0.0.0 dev script.

Hey, I resolved by updating node to 20.x

Refer command lines here : https://github.com/nodesource/distributions
